{
    "name": "Pump Station",
    "summary": """Pump Station""",
    "vesion":"15.0.8",
    "category": "Sales",
    "author": "Team Maulik",
    "application": True,
    "installable": True,
    "auto_install": False,
    "depends": ["base",
                "stock",
                "account", 
               ],
    "excludes": [],
    "data": [
             "security/approve_manager_security.xml", 
             "security/ir.model.access.csv",
             "report/discount_report.xml",
             "report/tank_report_template.xml",
             
             "views/station_view.xml",
             "views/pump_view.xml",
             "views/tank_view.xml",
             "views/pump_reading_view.xml",
             "views/tank_reading_view.xml",
             "views/pump_shift_view.xml",
             "views/product_category_view.xml",
             "views/account.xml",
             "views/partner.xml",
             "views/res_config_settings.xml",
             "wizard/tank_reading_wizard.xml",
             "wizard/discount_report_wizard.xml",
            ],
    "demo": [],
    "qweb": [],
    'license': 'LGPL-3',
}
